version: '3.8'

services:
  api:
    build:
      context: api
    depends_on:
      - db
    volumes:
      - ./api:/data/app
      - ./scripts:/scripts
    ports:
      - '127.0.0.1:8080:80'
    env_file:
      - api/.env
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.0.28
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: 'User'
      MYSQL_USER: 'adam'
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db_data:/var/lib/mysql

secrets:
  db_root_password:
    file: ./db/root_password.txt
  db_password:
    file: ./db/password.txt

volumes:
  db_data:
